name: Bug Report
description: File a bug report.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Bug description
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Super Tag version
      description: Main menu > Three dots > About
      options:
        - "0.5.0"
      default: 0
    validations:
      required: true
  - type: textarea
    id: device
    attributes:
      label: What device are you seeing the problem on?
      description: The make and model of the device, eg. "Samsung Galaxy S21"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What version of Android are you using?
      options:
        - "15"
        - "14"
        - "13"
        - "12"
        - "11"
        - "10"
        - "9"
      default: 0
    validations:
      required: true
