name: Bug Report
description: File a bug report.
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen? Add screenshots if possible.
      placeholder: Bug description
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Super Tag version
      description: Main menu > Three dots > About
      options:
        - "0.5.0"
      default: 0
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: What device are you seeing the problem on?
      description: The make and model of the device, eg. "Samsung Galaxy S21"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What version of Android are you using?
      options:
        - "15"
        - "14"
        - "13"
        - "12"
        - "11"
        - "10"
        - "9"
      default: 0
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Additional Information
      options:
        - label: I have checked that this bug has not been already reported by other users
          required: true
