name: Feature Request
description: Suggest a new feature or improvement.
labels: ["feature-request"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like to see? How would it improve your experience?
      placeholder: Feature description
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Additional Information
      options:
        - label: I have checked that this feature has not been already submitted by other users
          required: true
